import '@/styles/globals.scss';
import type { Metadata } from 'next';
import { dir } from 'i18next';
import { languages } from '@/i18n/settings';
import clsx from 'clsx';
import { sfProExpandedFont, sfProFont } from '@/config/fonts';
import Layout from '@/components/common/layout';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export async function generateStaticParams() {
  return languages.map((lng: any) => ({ lng }));
}

type Props = {
  children: React.ReactNode;
  params: {
    lang: string;
  };
};

export default function RootLayout({ children, params: { lang } }: Props) {
  return (
    <html lang={lang} dir={dir(lang)}>
      <body
        className={clsx(
          sfProFont.variable,
          sfProExpandedFont,
          'text-yellow-950 font-sf-pro',
        )}
      >
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
